## @(#) : lefthook config
#
# @version 1.0.1
# @author  atsushifx <atsushifx@gmail.com>
# @date    2024-02-05
# @license MIT
#
# @desc<<
#
# Configuration for Lefthook, a tool to manage and run Git hooks.
# Ensures hooks are consistently applied across all repositories
# for tasks like linting, testing, and formatting.
#
#<<

pre-commit:
  parallel: true
  commands:
    gitleaks:
      run: gitleaks protect --staged

    secretlint:
      glob: "**/*"
      run: secretlint --maskSecrets --no-color --secretlintignore .gitignore "{staged_files}"

    dprint:
      run: pnpm run check:dprint --staged .

#   eslint:
#     skip: true
#     run: pnpm run lint "{staged_files}"

#   eslint:types:
#     skip: true
#     run: pnpm run lint:types "{staged_files}"

# check commit message style
commit-msg:
  parallel: true
  commands:
    commitlint:
      run: commitlint -e
