## @(#) : secretlint config file for workspace
#
# @version   1.0.0
# @since     2025-04-12
# @author    Furukawa, Atsushi <atsushifx@aglabo.com>
# @license   MIT
#
# @description<<
#
# Secretlint configuration for scanning secrets and credentials.
# Applies recommended rules to catch accidental secrets in source code.
#
#<<

rules:
  - id: "@secretlint/secretlint-rule-preset-recommend"

# Example for custom rules:
# - id: "@secretlint/secretlint-rule-example"
#   options:
#     allowPatterns:
#       - "^TEST_SECRET_.*"
